const data = [
  {
    id: 'en-us-x-iog-network',
    language: 'en-US',
    latency: 200,
    name: 'en-us-x-iog-network',
    networkConnectionRequired: true,
    notInstalled: false,
    quality: 400,
  },
  {
    id: 'fr-fr-x-frd-local',
    language: 'fr-FR',
    latency: 200,
    name: 'fr-fr-x-frd-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'en-GB-language',
    language: 'en-GB',
    latency: 200,
    name: 'en-GB-language',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'nl-nl-x-dma-network',
    language: 'nl-NL',
    latency: 200,
    name: 'nl-nl-x-dma-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'en-gb-x-rjs-local',
    language: 'en-GB',
    latency: 200,
    name: 'en-gb-x-rjs-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'en-IN-language',
    language: 'en-IN',
    latency: 200,
    name: 'en-IN-language',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'cmn-cn-x-ccd-network',
    language: 'zh-CN',
    latency: 200,
    name: 'cmn-cn-x-ccd-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'tr-TR-language',
    language: 'tr-TR',
    latency: 200,
    name: 'tr-TR-language',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'sv-se-x-lfs-network',
    language: 'sv-SE',
    latency: 200,
    name: 'sv-se-x-lfs-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'ko-kr-x-ism-network',
    language: 'ko-KR',
    latency: 200,
    name: 'ko-kr-x-ism-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'cmn-cn-x-ccd-local',
    language: 'zh-CN',
    latency: 200,
    name: 'cmn-cn-x-ccd-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'gu-in-x-gum-local',
    language: 'gu-IN',
    latency: 200,
    name: 'gu-in-x-gum-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'de-de-x-nfh-network',
    language: 'de-DE',
    latency: 200,
    name: 'de-de-x-nfh-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'en-gb-x-gbb-local',
    language: 'en-GB',
    latency: 200,
    name: 'en-gb-x-gbb-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'gu-in-x-guf-local',
    language: 'gu-IN',
    latency: 200,
    name: 'gu-in-x-guf-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'bn-bd-x-ban-network',
    language: 'bn-BD',
    latency: 200,
    name: 'bn-bd-x-ban-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'hi-IN-language',
    language: 'hi-IN',
    latency: 200,
    name: 'hi-IN-language',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'en-au-x-aub-local',
    language: 'en-AU',
    latency: 200,
    name: 'en-au-x-aub-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'pt-pt-x-jmn-network',
    language: 'pt-PT',
    latency: 200,
    name: 'pt-pt-x-jmn-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'te-in-x-tem-local',
    language: 'te-IN',
    latency: 200,
    name: 'te-in-x-tem-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'cmn-tw-x-cte-network',
    language: 'zh-TW',
    latency: 200,
    name: 'cmn-tw-x-cte-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'pt-pt-x-sfs-local',
    language: 'pt-PT',
    latency: 200,
    name: 'pt-pt-x-sfs-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'nb-no-x-rfj-network',
    language: 'nb-NO',
    latency: 200,
    name: 'nb-no-x-rfj-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'fr-ca-x-caa-local',
    language: 'fr-CA',
    latency: 200,
    name: 'fr-ca-x-caa-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'ml-in-x-mlm-network',
    language: 'ml-IN',
    latency: 200,
    name: 'ml-in-x-mlm-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'kn-in-x-knf-local',
    language: 'kn-IN',
    latency: 200,
    name: 'kn-in-x-knf-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'fr-FR-language',
    language: 'fr-FR',
    latency: 200,
    name: 'fr-FR-language',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'en-in-x-ena-network',
    language: 'en-IN',
    latency: 200,
    name: 'en-in-x-ena-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'en-us-x-iol-network',
    language: 'en-US',
    latency: 200,
    name: 'en-us-x-iol-network',
    networkConnectionRequired: true,
    notInstalled: false,
    quality: 400,
  },
  {
    id: 'ta-in-x-tag-local',
    language: 'ta-IN',
    latency: 200,
    name: 'ta-in-x-tag-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'cmn-cn-x-cce-network',
    language: 'zh-CN',
    latency: 200,
    name: 'cmn-cn-x-cce-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'et-ee-x-tms-network',
    language: 'et-EE',
    latency: 200,
    name: 'et-ee-x-tms-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'en-in-x-end-network',
    language: 'en-IN',
    latency: 200,
    name: 'en-in-x-end-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'en-ng-x-tfn-local',
    language: 'en-NG',
    latency: 200,
    name: 'en-ng-x-tfn-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'fr-fr-x-frc-local',
    language: 'fr-FR',
    latency: 200,
    name: 'fr-fr-x-frc-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'fil-ph-x-fic-network',
    language: 'fil-PH',
    latency: 200,
    name: 'fil-ph-x-fic-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'bn-in-x-bnf-network',
    language: 'bn-IN',
    latency: 200,
    name: 'bn-in-x-bnf-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'fr-ca-x-caa-network',
    language: 'fr-CA',
    latency: 200,
    name: 'fr-ca-x-caa-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'bn-in-x-bnf-local',
    language: 'bn-IN',
    latency: 200,
    name: 'bn-in-x-bnf-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'vi-vn-x-vic-network',
    language: 'vi-VN',
    latency: 200,
    name: 'vi-vn-x-vic-network',
    networkConnectionRequired: true,
    notInstalled: false,
    quality: 400,
  },
  {
    id: 'ne-NP-language',
    language: 'ne-NP',
    latency: 200,
    name: 'ne-NP-language',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'en-in-x-ahp-network',
    language: 'en-IN',
    latency: 200,
    name: 'en-in-x-ahp-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'vi-vn-x-vid-local',
    language: 'vi-VN',
    latency: 200,
    name: 'vi-vn-x-vid-local',
    networkConnectionRequired: false,
    notInstalled: false,
    quality: 400,
  },
  {
    id: 'fi-fi-x-afi-local',
    language: 'fi-FI',
    latency: 200,
    name: 'fi-fi-x-afi-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'hi-in-x-hid-local',
    language: 'hi-IN',
    latency: 200,
    name: 'hi-in-x-hid-local',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'el-GR-language',
    language: 'el-GR',
    latency: 200,
    name: 'el-GR-language',
    networkConnectionRequired: false,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'vi-vn-x-gft-local',
    language: 'vi-VN',
    latency: 200,
    name: 'vi-vn-x-gft-local',
    networkConnectionRequired: false,
    notInstalled: false,
    quality: 400,
  },
  {
    id: 'ko-kr-x-kod-network',
    language: 'ko-KR',
    latency: 200,
    name: 'ko-kr-x-kod-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'da-dk-x-sfp-network',
    language: 'da-DK',
    latency: 200,
    name: 'da-dk-x-sfp-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
  {
    id: 'fr-fr-x-frc-network',
    language: 'fr-FR',
    latency: 200,
    name: 'fr-fr-x-frc-network',
    networkConnectionRequired: true,
    notInstalled: true,
    quality: 400,
  },
];
