// Action Types

export const LOGIN_EMAIL = 'LOGIN_EMAIL';
export const SAVE_USER_INFO_ASYNC = 'SAVE_USER_INFO_ASYNC';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING';
export const CANCEL_LOGIN = 'CANCEL_LOGIN';
export const LOGIN_USER_SUCCEED = 'LOGIN_USER_SUCCEED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
